### ISSUE TITLE
UMAP Plot: Pan, Zoom, Hover and Tooltip collision

### ISSUE THREAD

**Issue by danielreti** [populationgenomics/exome-results-browsers#12]
Difficult to make these 4 features co-exist as they consume the same mouse events.

**Comment by daniaki** [comment]
Would [this d3 plugin](https://github.com/d3/d3-zoom) avoid event collisions?

**Comment by danielreti** [comment]
Potentially. Pan and Zoom should be ok I think as they are click-based. I think the main issues is that the @gnomad/ui tooltip is consuming the mouse event for hover so the cluster highlighting doesn't get triggered. A workaround might be to write our own tooltip which gets triggered along with the cluster highlighting on hover. Otherwise there might be a way to change the @gnomad tooltip so it allows the event to propagate.

**Comment by daniaki** [comment]
Oh I see. I think we should take inspiration from [this](https://github.com/broadinstitute/gnomad-browser-toolkit/blob/cb9adfefcb6bec52c57f399c355cf2d98bbaf70b/packages/qq-plot/src/QQPlot.js#L249) gnomAD plot and create an SVG tooltip on hover and avoid using the @gnomad/ui collection inside plots.

**Comment by danielreti** [comment]
That looks promising, will take a look!

**Comment by danielreti** [comment]
Implemented zooming, panning and hovering simultaneously - significant performance issues rendering >11000 data points.
Will work on custom tooltip + search for performance solutions.

**Comment by daniaki** [comment]
Retiring this issue since UMAP will be re-implemented using Nebulosa's method
